name: CI

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}-latest
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]')
        || contains(github.event.head_commit.message, '[ci skip]')
        || contains(github.event.head_commit.message, '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ 2.7, 3.0, 3.1, 3.2, 3.3, jruby-9.3, jruby-9.4 ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the tests
        timeout-minutes: 10
        run: bundle exec rake spec
